# Generated by Django 4.1.5 on 2023-02-14 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoEmpleado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Persona2",
            fields=[
                (
                    "rfc",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100, null=True)),
                ("es_empleado", models.BooleanField(default=False)),
                ("edad", models.IntegerField(default=0)),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 14, 13, 3, 26, 691668)
                    ),
                ),
                (
                    "sueldo",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("altura", models.FloatField(null=True)),
                ("cintura", models.TextField(null=True)),
                (
                    "tipo_empleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appPersonal.tipoempleado",
                    ),
                ),
            ],
        ),
    ]
