# Generated by Django 4.0.4 on 2022-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_factura', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('rama', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('linea_de_producto', models.CharField(max_length=100)),
                ('precio_por_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
