# Generated by Django 4.0.4 on 2022-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_factura',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
