# Generated by Django 4.0.4 on 2022-05-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventas_id_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
